### PR TITLE
:arrow_up: [Version] Update to version 1.0.0

### LINKED ISSUE #49: Graduate Fuse to version 1.0

### PR DESCRIPTION
**Pull request by kittinunf**
### Description

This bump fuse to version 1.0.0 together with update of Kotlinx serialization to the latest version

close #49

### CODE REVIEW

**Review by zalewskise — APPROVED** [review]
Awesome!

**Comment by zalewskise** [comment]
@kittinunf I think you can also update Kotlin to 1.4.20

**Comment by kittinunf** [comment]
Oh okay ... let me update on this PR as well.

**Review by zalewskise — APPROVED** [review]
🐐  🥇

**Pull request merged**
