### PR TITLE
Integrate Code cov into project

### PR DESCRIPTION
**Pull request by kittinunf**
### What's in this PR?

### CODE REVIEW

**Comment by kittinunf** [comment]
Ouch, this doesn't seem to be working.

**Comment by babedev** [comment]
wow, it's coming

**Comment by kittinunf** [comment]
Yes 😅. It turns out that we need to use AS 2.3 syntax for now like `compile` and `testCompile` instead of `implementation` `api`, etc ... 

This PR should be completed :) I will merge as soon as you give it a go.

**Comment by babedev** [comment]
Looks great. Let's merge this one 😄

**Pull request merged**
